chore: bump cosign installer to 3.0.2 to avoid downstream failures due to invalid key format
cosign 3.0.1 is buggy and will error out with:

```
main.go:74: error during command execution: signing [ghcr.io/doosty/Ublue-Hyprland@sha256:fc10c28ba044c6f3590124d0dff5f462c8cb6f1c39b001718c1e52c8e4723e8f]: getting signer: reading key: unsupported pem type: ENCRYPTED SIGSTORE PRIVATE KEY
```